# Generated by Django 5.2.5 on 2025-08-18 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('REQUEST', 'Request'), ('JOB', 'Job')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='network.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
