# Generated by Django 5.2.5 on 2025-08-28 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizzboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
