# Generated by Django 5.2.5 on 2025-08-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ARTICLE', 'Article'), ('REPORT', 'Report'), ('WEBINAR', 'Webinar'), ('VIDEO', 'Video'), ('INFOGRAPHIC', 'Infographic')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('published_at', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-published_at', 'title'],
            },
        ),
    ]
